### ISSUE TITLE
明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版

### ISSUE THREAD

**Issue by zch133** [injahow/user.js#57]
![image](https://github.com/injahow/user.js/assets/114413595/f6fccbb8-69c1-4215-893c-0c3358889cdb)

**Comment by zhangkaidhb** [comment]
我也遇到了相同的问题

**Comment by injahow** [comment]
> ![image](https://user-images.githubusercontent.com/114413595/278373620-f6fccbb8-69c1-4215-893c-0c3358889cdb.png)

发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是  v2.4.6 6764ccb

**Comment by zhangkaidhb** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误.
        
            
        
    
    
        
            
        
    
    
     
    
        
                    Kai ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月29日 14:04
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57)
        
      
    
  
  



发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是  v2.4.6 6764ccb

**Comment by injahow** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年10月29日 14:04 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 [6764ccb](https://github.com/injahow/user.js/commit/6764ccb6ead9705be317fedf0e55b0037df1a4b1) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

把脚本设置发一下看看

**Comment by zhangkaidhb** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    脚本设置指的是代码吗?
        
    
        
            
        
    
    
     
    
        
                    Kai ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月29日 14:13
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57)
        
      
    
  
  

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.***
…
---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 6764ccb —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

把脚本设置发一下看看

**Comment by injahow** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 脚本设置指的是代码吗? Kai ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年10月29日 14:13 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.*** … ---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 [6764ccb](https://github.com/injahow/user.js/commit/6764ccb6ead9705be317fedf0e55b0037df1a4b1) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> 把脚本设置发一下看看 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

![image](https://github.com/injahow/user.js/assets/42839062/125399ad-dccf-4505-8e33-898ae1d7aa0c)

**Comment by zhangkaidhb** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    是这个吗?
        
            
        
    
    
        
            
        
    
    
     
    
        
                    Kai ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月29日 14:13
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57)
        
      
    
  
  

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.***
…
---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 6764ccb —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

把脚本设置发一下看看

**Comment by injahow** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 是这个吗? Kai ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年10月29日 14:13 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.*** … ---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 [6764ccb](https://github.com/injahow/user.js/commit/6764ccb6ead9705be317fedf0e55b0037df1a4b1) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> 把脚本设置发一下看看 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

发的什么？空白的

**Comment by zhangkaidhb** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    下面邮件发过了,是这个吧
    
        
            
        
    
    
     
    
        
                    Kai ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月29日 14:20
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57)
        
      
    
  
  

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 脚本设置指的是代码吗? Kai @.***
…
---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:13 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.*** … ---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 6764ccb —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 把脚本设置发一下看看 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

**Comment by injahow** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 下面邮件发过了,是这个吧 Kai ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年10月29日 14:20 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 脚本设置指的是代码吗? Kai @.*** … ---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:13 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.*** … ---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 [6764ccb](https://github.com/injahow/user.js/commit/6764ccb6ead9705be317fedf0e55b0037df1a4b1) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 把脚本设置发一下看看 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

![image](https://github.com/injahow/user.js/assets/42839062/e77736bf-3d64-4fa8-8c67-70d7148a9da1)
这个

**Comment by zhangkaidhb** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你那边好像看不到我发的图片,我放附件试一下.
        
    
        
            
        
    
    
     
    
        
                    Kai ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月29日 14:22
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57)
        
      
    
  
  

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 是这个吗? Kai @.***
…
---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:13 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Hi 大佬,我这边各项信息如下:控制台版本是2.4.6  单个视频请求没问题,但是点批量下载就会报当前版本不支持的错误.包括在脚本设置中点击账号授权,手动授权都会报同样的错误. Kai @.*** … ---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年10月29日 14:04 收件人 @.> 抄送人 @.> , @.> 主题 Re: [injahow/user.js] 明明更新到最新版但是却在给账号授权时说该版本不支持该功能请升级到最新版 (Issue #57) 发一下请求报文看看，请求地址是预置的吗，看看控制台版本是不是 v2.4.6 6764ccb —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 把脚本设置发一下看看 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

发的什么？空白的

**Comment by iMISSmilk** [comment]
大大，跟一楼一样也是遇到一样问题：该版本已不支持当前功能，请升级新版本！最新2.4.6，脚本设置都是默认的没动过。上个月还可以的。浏览器重装后，重新加您的插件就不行了

**Comment by zch133** [comment]
![image](https://github.com/injahow/user.js/assets/114413595/87301ed9-c4c0-4ff9-8b50-c967af4d48c3)

**Comment by zch133** [comment]
![image](https://github.com/injahow/user.js/assets/114413595/9fd3a4a9-67cd-4cec-a2c7-80c2f4f7d8f8)

**Comment by zch133** [comment]
大大我其他设置都没变，以前这样子都能授权成功，现在就不行了

**Comment by injahow** [comment]
> 大大我其他设置都没变，以前这样子都能授权成功，现在就不行了

能否在开发者工具查看一下的http请求报文，发一下授权时的返回这个消息的请求头信息

**Comment by injahow** [comment]
额。。。看了下好像是b站弃用这个第三方登陆了，目前脚本应该是是不支持登陆了
